# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Quote.mn admin panel
    description:  symfony project
    keywords:     symfony, project
    language:     en
    robots:       index, nofollow

  stylesheets:    
    - /assets/bootstrap/css/bootstrap.min.css
    - /assets/font-awesome/css/font-awesome.css
    - main.css

  javascripts:    
    - /assets/jquery/jquery-1.11.0.js
    - /assets/bootstrap/js/bootstrap.min.js

  has_layout:     true
  layout:         layout
