<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('QuoteAuthorType', 'doctrine');

/**
 * BaseQuoteAuthorType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property integer $created_user_id
 * @property integer $is_top
 * @property integer $is_featured
 * @property integer $is_active
 * @property timestamp $published_at
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer         getId()              Returns the current record's "id" value
 * @method string          getTitle()           Returns the current record's "title" value
 * @method integer         getCreatedUserId()   Returns the current record's "created_user_id" value
 * @method integer         getIsTop()           Returns the current record's "is_top" value
 * @method integer         getIsFeatured()      Returns the current record's "is_featured" value
 * @method integer         getIsActive()        Returns the current record's "is_active" value
 * @method timestamp       getPublishedAt()     Returns the current record's "published_at" value
 * @method timestamp       getCreatedAt()       Returns the current record's "created_at" value
 * @method timestamp       getUpdatedAt()       Returns the current record's "updated_at" value
 * @method QuoteAuthorType setId()              Sets the current record's "id" value
 * @method QuoteAuthorType setTitle()           Sets the current record's "title" value
 * @method QuoteAuthorType setCreatedUserId()   Sets the current record's "created_user_id" value
 * @method QuoteAuthorType setIsTop()           Sets the current record's "is_top" value
 * @method QuoteAuthorType setIsFeatured()      Sets the current record's "is_featured" value
 * @method QuoteAuthorType setIsActive()        Sets the current record's "is_active" value
 * @method QuoteAuthorType setPublishedAt()     Sets the current record's "published_at" value
 * @method QuoteAuthorType setCreatedAt()       Sets the current record's "created_at" value
 * @method QuoteAuthorType setUpdatedAt()       Sets the current record's "updated_at" value
 * 
 * @package    quote.mn
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuoteAuthorType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quote_author_type');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_top', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_featured', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('published_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}