<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Quote', 'doctrine');

/**
 * BaseQuote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $body
 * @property integer $author_id
 * @property integer $category_id
 * @property integer $created_user_id
 * @property integer $is_top
 * @property integer $is_featured
 * @property integer $is_active
 * @property timestamp $published_at
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer   getId()              Returns the current record's "id" value
 * @method string    getBody()            Returns the current record's "body" value
 * @method integer   getAuthorId()        Returns the current record's "author_id" value
 * @method integer   getCategoryId()      Returns the current record's "category_id" value
 * @method integer   getCreatedUserId()   Returns the current record's "created_user_id" value
 * @method integer   getIsTop()           Returns the current record's "is_top" value
 * @method integer   getIsFeatured()      Returns the current record's "is_featured" value
 * @method integer   getIsActive()        Returns the current record's "is_active" value
 * @method timestamp getPublishedAt()     Returns the current record's "published_at" value
 * @method timestamp getCreatedAt()       Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()       Returns the current record's "updated_at" value
 * @method Quote     setId()              Sets the current record's "id" value
 * @method Quote     setBody()            Sets the current record's "body" value
 * @method Quote     setAuthorId()        Sets the current record's "author_id" value
 * @method Quote     setCategoryId()      Sets the current record's "category_id" value
 * @method Quote     setCreatedUserId()   Sets the current record's "created_user_id" value
 * @method Quote     setIsTop()           Sets the current record's "is_top" value
 * @method Quote     setIsFeatured()      Sets the current record's "is_featured" value
 * @method Quote     setIsActive()        Sets the current record's "is_active" value
 * @method Quote     setPublishedAt()     Sets the current record's "published_at" value
 * @method Quote     setCreatedAt()       Sets the current record's "created_at" value
 * @method Quote     setUpdatedAt()       Sets the current record's "updated_at" value
 * 
 * @package    quote.mn
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseQuote extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('quote');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('author_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('category_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_top', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_featured', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('published_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}