<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Category', 'doctrine');

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $model_name
 * @property integer $parent_id
 * @property string $title
 * @property integer $sort
 * @property integer $is_active
 * @property integer $created_user_id
 * @property timestamp $updated_at
 * @property timestamp $created_at
 * 
 * @method integer   getId()              Returns the current record's "id" value
 * @method string    getModelName()       Returns the current record's "model_name" value
 * @method integer   getParentId()        Returns the current record's "parent_id" value
 * @method string    getTitle()           Returns the current record's "title" value
 * @method integer   getSort()            Returns the current record's "sort" value
 * @method integer   getIsActive()        Returns the current record's "is_active" value
 * @method integer   getCreatedUserId()   Returns the current record's "created_user_id" value
 * @method timestamp getUpdatedAt()       Returns the current record's "updated_at" value
 * @method timestamp getCreatedAt()       Returns the current record's "created_at" value
 * @method Category  setId()              Sets the current record's "id" value
 * @method Category  setModelName()       Sets the current record's "model_name" value
 * @method Category  setParentId()        Sets the current record's "parent_id" value
 * @method Category  setTitle()           Sets the current record's "title" value
 * @method Category  setSort()            Sets the current record's "sort" value
 * @method Category  setIsActive()        Sets the current record's "is_active" value
 * @method Category  setCreatedUserId()   Sets the current record's "created_user_id" value
 * @method Category  setUpdatedAt()       Sets the current record's "updated_at" value
 * @method Category  setCreatedAt()       Sets the current record's "created_at" value
 * 
 * @package    quote.mn
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('model_name', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('parent_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('sort', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}