<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }
    
    public function getCategorysByParentId($parent_id, $model_name)
    {
        $q = self::getInstance()->createQuery('a')
                ->where('a.parent_id = ?', $parent_id)
                ->andWhere('a.model_name=?', $model_name)
                ->orderBy('a.sort ASC');
        
        return $q->execute();
    }
    public function getCategories($model_name)
    {
        $categories = Doctrine_Core::getTable('Category')
            ->createQuery('a')
            ->andWhere('a.model_name=?', $model_name)
            ->orderBy('a.sort ASC')
            ->execute();
        return $categories;
    }
}