<?php

/**
 * PageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Page');
    }
    public function getPagesByParentId($parent_id)
    {
        $q = self::getInstance()->createQuery()
                ->where('parent_id = ?', $parent_id)
                ->orderBy('id ASC');
        
        return $q->execute();
    }
    
    public function getModulePagesMenu()
    {
        return Doctrine_Core::getTable('Page')
                ->createQuery('a')
                ->andWhere('a.is_in_menu=1')
                ->andWhere('a.is_active=1')
                ->orderBy('a.sort ASC')
                ->execute();
    }
    public function getModulePagesMenuDraft()
    {
        return Doctrine_Core::getTable('Page')
                ->createQuery('a')
                ->andWhere('a.is_in_menu=1')
                ->andWhere('a.is_active=0')
                ->orderBy('a.sort ASC')
                ->execute();
    }
    public function getModulePagesHidden()
    {
        return Doctrine_Core::getTable('Page')
                ->createQuery('a')
                ->andWhere('a.is_in_menu=0')
                ->andWhere('a.is_active=1')
                ->orderBy('a.sort ASC')
                ->execute();
    }
    public function getModulePagesHiddenDraft()
    {
        return Doctrine_Core::getTable('Page')
                ->createQuery('a')
                ->andWhere('a.is_in_menu=0')
                ->andWhere('a.is_active=0')
                ->orderBy('a.sort ASC')
                ->execute();
    }
}