<?php

/**
 * Post
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ecommerce
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Post extends BasePost
{
    public function getCategory()
    {
        $category = Doctrine_Core::getTable('PostCategory')->find($this->getCategoryId());
        
        if($category)
            return $category;
        else
            return new PostCategory();
    }
    public function getUser()
    {
        $user = Doctrine_Core::getTable('User')->find($this->getCreatedUserId());
        
        if($user)
            return $user;
        else
            return new User();
    }

}
