<?php

/**
 * QuoteCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    quote.mn
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class QuoteCategory extends BaseQuoteCategory
{
  public function Publish()
  {
    $this->setIsActive('1');
    if($this->getPublishedAt() == '0000-00-00 00:00:00')
    {
      $this->setPublishedAt(date('Y-m-d H:i:s'));
    }
    $this->save();
  }
}