<?php

/**
 * QuoteAuthorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuoteAuthorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuoteAuthorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuoteAuthor');
    }
}