<?php

/**
 * QuoteAuthorTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuoteAuthorTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuoteAuthorTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuoteAuthorType');
    }
}