<?php

/**
 * QuoteCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class QuoteCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object QuoteCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('QuoteCategory');
    }
}